# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      id: setup-node
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Dynamic vers
      id: vers
      run: |
        echo "::set-output name=node::$(node -v)"

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          .next
          node_modules
        key: npm-v1-${{ runner.os }}-${{ steps.vers.outputs.node }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          npm-v1-${{ runner.os }}-${{ steps.vers.outputs.node }}-
          npm-v1-${{ runner.os }}-

    - run: yarn install

    - run: yarn build

    - run: yarn test
