# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      id: setup-node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Dynamic vers
      id: vers
      run: |
        echo "::set-output name=node::$(node -v)"

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          .next
          node_modules
        key: npm-v1-${{ runner.os }}-${{ steps.vers.outputs.node }}-${{ hashFiles('.yarnclean') }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          npm-v1-${{ runner.os }}-${{ steps.vers.outputs.node }}-${{ hashFiles('.yarnclean') }}-
          npm-v1-${{ runner.os }}-${{ steps.vers.outputs.node }}-

    - run: yarn install

    - run: yarn build

    - run: yarn test

    - uses: actions/upload-artifact@v2
      with:
        name: coverage-artifact
        path: |
          coverage/
          src/

  upload-coverage:

    needs: [build]

    runs-on: ubuntu-latest

    timeout-minutes: 2

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage-artifact

      - uses: codecov/codecov-action@v1

